"""Data models for the tabular_agent component."""

from __future__ import annotations

from pydantic import BaseModel, Field

# Maximum characters kept per rendered value when describing a column.
_VALUE_CHARS = 60


class GeneratedSQL(BaseModel):
    """A SQL query generated by the LLM from a natural-language question."""

    sql: str = Field(
        ...,
        description="A single read-only DuckDB SELECT (a leading WITH is allowed).",
    )
    reasoning: str = Field(
        ...,
        max_length=500,
        description="Brief explanation of how the query answers the question.",
    )


class SheetLayout(BaseModel):
    """Where the real table sits inside a messy spreadsheet sheet.

    Produced by the LLM only when the deterministic heuristics cannot work the
    layout out on their own. All row/column numbers are **0-based indices into
    the raw sheet grid**, counting every row including blank ones.
    """

    header_row: int = Field(
        ...,
        description="0-based index of the row holding the column headers.",
    )
    data_start_row: int = Field(
        ...,
        description="0-based index of the first data row (usually header_row + 1).",
    )
    data_end_row: int | None = Field(
        default=None,
        description=(
            "0-based index of the last data row, inclusive. Null means 'to the end'. "
            "Set this to exclude trailing totals or notes."
        ),
    )
    skip_columns: list[int] = Field(
        default_factory=list,
        description="0-based indices of columns to drop (blank spacers, notes).",
    )
    reasoning: str = Field(
        ...,
        max_length=500,
        description="Brief explanation of how the layout was determined.",
    )


class ColumnProfile(BaseModel):
    """A single column, described richly enough for an LLM to write SQL over it."""

    name: str
    data_type: str
    null_fraction: float = Field(default=0.0, description="Share of NULL values, 0.0-1.0.")
    distinct_count: int = 0
    min_value: str | None = None
    max_value: str | None = None
    top_values: list[str] = Field(
        default_factory=list,
        description="Most frequent values, for low-cardinality columns only.",
    )
    samples: list[str] = Field(default_factory=list)


class TableProfile(BaseModel):
    """One loaded table: where it came from, how big it is, what is in it."""

    name: str
    source: str = Field(description="Originating file, plus sheet name for Excel.")
    row_count: int = 0
    columns: list[ColumnProfile] = Field(default_factory=list)


class TabularSchema(BaseModel):
    """Every table the agent can query, with per-column profiles."""

    tables: list[TableProfile] = Field(default_factory=list)

    @property
    def table_names(self) -> list[str]:
        """Names of every loaded table."""
        return [t.name for t in self.tables]

    def to_prompt_text(self) -> str:
        """Render a compact, LLM-friendly description of the loaded data.

        Column statistics matter as much as the column names here: knowing that
        ``status`` only ever holds three values, or that ``amount`` is 40% NULL,
        is what stops the model from inventing filters that match nothing.
        """
        if not self.tables:
            return "(no tables loaded)"
        blocks: list[str] = []
        for table in self.tables:
            lines = [f"TABLE {table.name}  -- from {table.source}, {table.row_count} row(s)"]
            lines.append("(")
            for col in table.columns:
                lines.append(f"  {col.name} {col.data_type}{_describe_column(col)}")
            lines.append(")")
            blocks.append("\n".join(lines))
        return "\n\n".join(blocks)


def _describe_column(col: ColumnProfile) -> str:
    """Render the statistical annotations that follow a column's type."""
    notes: list[str] = []
    if col.null_fraction >= 0.005:
        notes.append(f"{col.null_fraction:.0%} NULL")
    if col.distinct_count:
        notes.append(f"{col.distinct_count} distinct")
    if col.min_value is not None and col.max_value is not None:
        notes.append(f"range {_clip(col.min_value)}..{_clip(col.max_value)}")
    if col.top_values:
        notes.append("values: " + ", ".join(_clip(v) for v in col.top_values))
    elif col.samples:
        notes.append("e.g. " + ", ".join(_clip(v) for v in col.samples))
    return "  -- " + "; ".join(notes) if notes else ""


def _clip(text: str) -> str:
    """Shorten a rendered value so one wide column cannot flood the prompt."""
    return text if len(text) <= _VALUE_CHARS else text[:_VALUE_CHARS] + "…"


class QueryResult(BaseModel):
    """Outcome of the agentic text-to-SQL loop for one question."""

    question: str
    sql: str | None = None
    reasoning: str | None = None
    rows: list[dict] = Field(default_factory=list)
    row_count: int = 0
    attempts: int = 0
    succeeded: bool = False
    error: str | None = None


class AnswerResult(BaseModel):
    """A natural-language answer plus the QueryResult it was derived from."""

    question: str
    answer: str
    query_result: QueryResult
