#!/usr/bin/env node
/**
 * Customer test report status: docs/customer-report-2026-09-28.json -> .md
 *
 * Every finding marked "fixed" names the tests that hold it fixed. This resolves
 * each reference against the working tree, so a renamed or deleted test breaks
 * the build instead of leaving a finding that looks covered and is not — the
 * same rule scripts/acceptance-matrix.mjs applies to the sprint criteria.
 *
 * Usage:
 *   node scripts/customer-report.mjs           # check refs + rewrite the doc
 *   node scripts/customer-report.mjs --check   # check refs only (CI)
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const appRoot = path.join(path.dirname(fileURLToPath(import.meta.url)), "..");
const specPath = path.join(appRoot, "docs", "customer-report-2026-09-28.json");
const outPath = path.join(appRoot, "docs", "customer-report-2026-09-28.md");
const checkOnly = process.argv.includes("--check");

const spec = JSON.parse(fs.readFileSync(specPath, "utf8"));
const problems = [];
const fileCache = new Map();

function readSource(rel) {
  if (!fileCache.has(rel)) {
    const abs = path.join(appRoot, rel);
    fileCache.set(rel, fs.existsSync(abs) ? fs.readFileSync(abs, "utf8") : null);
  }
  return fileCache.get(rel);
}

/** A test reference is good when the file exists and names the test. */
function checkEvidence(ref, ev) {
  if (ev.file === "—") return; // prose evidence, nothing to resolve
  const source = readSource(ev.file);
  if (source === null) {
    problems.push(`${ref}: file not found — ${ev.file}`);
    return;
  }
  if (!source.includes(ev.name)) {
    problems.push(`${ref}: "${ev.name}" not found in ${ev.file}`);
  }
}

const counts = { fixed: 0, open: 0, descoped: 0, sprint4: 0 };
for (const group of spec.groups) {
  for (const f of group.findings) {
    counts[f.status] = (counts[f.status] ?? 0) + 1;
    if (f.status === "fixed") {
      if (!f.evidence?.length) problems.push(`${f.ref}: marked fixed with no evidence`);
      for (const ev of f.evidence ?? []) checkEvidence(f.ref, ev);
    }
  }
}

if (problems.length) {
  console.error("Customer report references do not resolve:\n");
  for (const p of problems) console.error(`  - ${p}`);
  console.error("\nUpdate the reference, or the finding is not covered any more.");
  process.exit(1);
}

const MARK = { fixed: "**fixed**", open: "open", descoped: "descoped", sprint4: "Sprint 4" };

const lines = [];
lines.push(`# ${spec.title}`, "");
lines.push(spec.source, "");
lines.push(`Verified against \`${spec.verifiedAgainst}\`. ${spec.note}`, "");
lines.push(
  `**${counts.fixed} fixed · ${counts.open} open · ${counts.descoped ?? 0} out of scope by agreement · ${counts.sprint4 ?? 0} Sprint 4**`,
  "",
);

lines.push("## Test levels", "");
lines.push("| Level | What it runs | When |", "|---|---|---|");
for (const [, l] of Object.entries(spec.levels)) {
  lines.push(`| ${l.label} | \`${l.command}\` | ${l.runs} |`);
}
lines.push("");

for (const group of spec.groups) {
  lines.push(`## ${group.name}`, "");
  lines.push("| Finding | Status | Shipped in | Verified by |", "|---|---|---|---|");
  for (const f of group.findings) {
    const evidence = (f.evidence ?? [])
      .map((ev) => (ev.file === "—" ? ev.name : `\`${ev.name}\``))
      .join("<br>") || "—";
    lines.push(
      `| **${f.ref}** — ${f.text} | ${MARK[f.status]} | ${f.shippedIn ?? "—"} | ${evidence} |`,
    );
  }
  lines.push("");
  for (const f of group.findings) {
    if (f.caveat) lines.push(`> **${f.ref}.** ${f.caveat}`, "");
    if (f.openBecause) lines.push(`> **${f.ref}.** ${f.openBecause}`, "");
  }
}

lines.push("---", "");
lines.push(
  "Generated by `scripts/customer-report.mjs` from the JSON beside this file.",
  "Every test named above is resolved against the working tree when this runs, so a",
  "renamed or deleted test fails the check rather than leaving a finding that looks",
  "covered and is not.",
  "",
);

const markdown = lines.join("\n");
if (checkOnly) {
  const current = fs.existsSync(outPath) ? fs.readFileSync(outPath, "utf8") : "";
  if (current !== markdown) {
    console.error("docs/customer-report-2026-09-28.md is stale — run: npm run customer-report");
    process.exit(1);
  }
  console.log(`Customer report references resolve (${counts.fixed} fixed).`);
} else {
  fs.writeFileSync(outPath, markdown);
  console.log(`Wrote ${path.relative(appRoot, outPath)} — ${counts.fixed} fixed, ${counts.open} open.`);
}
