#!/usr/bin/env python3
"""Generate the extraction schema using the GAIK SchemaGenerator.

Called once during Phase 5 (Schema Design) of the wizard conversation.
The wizard presents the generated schema to the user for review; the user
approves or requests changes; approved changes are incorporated by the
wizard directly (no second SchemaGenerator call). The approved schema is
then saved and reused by run_poc.py via load_schema().

Flow:
    Phase 5 in SKILL.md:
        1. Call this script to generate the schema from extraction_requirements.md
        2. Present output_schema.py to the user for review
        3. User approves or requests changes (wizard edits directly, no re-generation)
        4. Confirmed schema is already saved -- scaffold_poc.py will use it as-is

Usage:
    python scripts/generate_schema.py \\
        --requirements poc/prompts/extraction_requirements.md \\
        --schema-name MaintenanceTicket \\
        --output-dir poc/
        [--use-azure / --no-azure]
        [--model gpt-5.4]
"""

from __future__ import annotations

import argparse
import importlib
import io
import json
import sys
from contextlib import redirect_stdout
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent / "src"))

# GAIK imports -- only needed at runtime, not at scaffold time
try:
    from gaik.software_components.config import get_openai_config
    from gaik.software_components.extractor.schema import (
        ExtractionRequirements,
        SchemaGenerator,
        print_pydantic_schema,
    )

    _GAIK_AVAILABLE = True
except ImportError as _import_err:
    _GAIK_AVAILABLE = False
    _IMPORT_ERR = _import_err


def _clean_schema_dump(raw: str) -> str:
    """Remove the header/footer separator lines print_pydantic_schema adds.

    The output format is:
        ================...  (header separator)
        Schema Title
        ================...  (header separator)
        <blank>
        class ClassName(...):
            ...
        ================...  (footer separator)   <-- must also be stripped
    """
    import re

    _sep = re.compile(r"^=+\s*$")
    lines = raw.splitlines()
    cleaned = []
    in_class = False
    for line in lines:
        if not in_class and line.startswith("class "):
            in_class = True
        if in_class:
            if _sep.match(line):
                continue  # skip footer separator
            cleaned.append(line)
    return "\n".join(cleaned).rstrip()


def _schema_to_py(schema_class: type, schema_name: str) -> str:
    """Render the generated Pydantic class to a .py file string."""
    buffer = io.StringIO()
    with redirect_stdout(buffer):
        print_pydantic_schema(schema_class, title="Saved Schema")
    schema_code = _clean_schema_dump(buffer.getvalue())

    # Determine the actual class name from the generated model
    actual_class_name = schema_class.__name__

    return (
        '"""Output schema for this use case.\n\n'
        "Generated by GAIK SchemaGenerator via the Solution Configuration Wizard.\n"
        "Reviewed and approved by the user during Phase 5 (Schema Design).\n"
        'Do not hand-edit -- re-run generate_schema.py if the requirements change.\n"""\n\n'
        "import decimal\n"
        "from decimal import Decimal\n"
        "from typing import List, Literal, Optional\n\n"
        "from pydantic import BaseModel, Field, ConfigDict\n\n"
        f"{schema_code}\n"
    )


def _requirements_to_json(
    schema_class: type,
    requirements: ExtractionRequirements,
) -> dict:
    """Produce the payload that load_schema() expects.

    ``requirements_type`` carries the structure across the round trip. Without
    it a parent-with-children record reloads as a flat ExtractionRequirements,
    and the component then copies the header fields onto every child row.
    """
    payload = {
        "model_name": schema_class.__name__,
        "requirements": requirements.model_dump(),
    }
    structure = getattr(requirements, "structure_type", None)
    if structure:
        payload["requirements_type"] = structure
    return payload


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate extraction schema via GAIK SchemaGenerator."
    )
    parser.add_argument(
        "--requirements",
        required=True,
        help="Path to extraction_requirements.md (user requirements text)",
    )
    parser.add_argument(
        "--schema-name",
        default=None,
        help="Expected class name (informational; SchemaGenerator decides the actual name)",
    )
    parser.add_argument(
        "--output-dir",
        required=True,
        help="PoC root directory -- schema files written to <output-dir>/schemas/",
    )
    parser.add_argument(
        "--use-azure",
        dest="use_azure",
        action="store_true",
        default=True,
        help="Use Azure OpenAI (default)",
    )
    parser.add_argument(
        "--no-azure",
        dest="use_azure",
        action="store_false",
        help="Use OpenAI directly instead of Azure",
    )
    parser.add_argument(
        "--model",
        default=None,
        help="Override the model used for schema generation",
    )
    args = parser.parse_args()

    if not _GAIK_AVAILABLE:
        print(
            f"ERROR: GAIK toolkit not available: {_IMPORT_ERR}\n"
            "Install with: pip install gaik[extract]",
            file=sys.stderr,
        )
        return 1

    req_path = Path(args.requirements)
    if not req_path.exists():
        print(f"ERROR: Requirements file not found: {req_path}", file=sys.stderr)
        return 1

    user_requirements = req_path.read_text(encoding="utf-8")
    output_dir = Path(args.output_dir).expanduser().resolve()
    schemas_dir = output_dir / "schemas"
    schemas_dir.mkdir(parents=True, exist_ok=True)

    print(f"Generating schema from: {req_path}")
    print(f"Output directory:       {schemas_dir}")
    print(f"Provider:               {'Azure OpenAI' if args.use_azure else 'OpenAI'}")
    print()

    # -- Call SchemaGenerator (one API call) --
    config = get_openai_config(use_azure=args.use_azure)
    generator = SchemaGenerator(config=config, model=args.model)
    schema_class = generator.generate_schema(user_requirements=user_requirements)
    requirements: ExtractionRequirements = generator.item_requirements

    # -- Write output_schema.py --
    py_content = _schema_to_py(schema_class, args.schema_name or schema_class.__name__)
    py_path = schemas_dir / "output_schema.py"
    py_path.write_text(py_content, encoding="utf-8")
    print(f"\nSchema written to:       {py_path}")

    # -- Write output_schema_requirements.json (load_schema() contract) --
    req_payload = _requirements_to_json(schema_class, requirements)
    req_path_out = schemas_dir / "output_schema_requirements.json"
    req_path_out.write_text(json.dumps(req_payload, indent=2), encoding="utf-8")
    print(f"Requirements written to: {req_path_out}")

    # -- Export JSON Schema (best-effort, for documentation) --
    try:
        json_schema = schema_class.model_json_schema()
        json_path = schemas_dir / "output_schema.json"
        json_path.write_text(json.dumps(json_schema, indent=2), encoding="utf-8")
        print(f"JSON Schema written to:  {json_path}")
    except Exception:
        pass

    # -- Save requirements hash so run_poc.py knows the schema is current --
    # If extraction_requirements.md is later edited, the hash mismatch will
    # trigger regeneration on the next run_poc.py invocation.
    import hashlib

    req_hash = hashlib.sha256(req_path.read_bytes()).hexdigest()
    # All schema files are always named output_schema.* regardless of the class
    # name. The hash file is therefore always output_schema.hash so that every
    # PoC template's _load_schema_if_fresh() finds it with schema_name="output_schema".
    hash_path = schemas_dir / "output_schema.hash"
    hash_path.write_text(req_hash)
    print(f"Requirements hash saved: {hash_path}")

    print(
        f"\nGenerated class name: {schema_class.__name__}"
        f"\nFields: {[f.field_name for f in requirements.fields]}"
        f"\n\nPresent {py_path} to the user for review."
        "\nIf the user requests changes, edit output_schema.py and"
        "\noutput_schema_requirements.json directly -- do NOT re-run this script."
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
