import type { Locale } from "@/lib/i18n";

/** Texts of the case view (the generated solution in use). Kept beside it, not in Dict. */
export type CaseStrings = typeof fi;

const fi = {
  kicker: "Ratkaisu käytössä",
  intro: "Roolit ja vaiheet tulevat ratkaisun BPMN-kaaviosta, lomake sovituista tuloskentistä. Tekoälyvaihe ajetaan sandboxissa tapauksen omalla syötteellä.",
  back: "Takaisin wizardiin",
  newCase: "Uusi tapaus",
  cases: "Tapaukset",
  noCases: "Ei tapauksia vielä.",
  notReady: "Paketti ei ole vielä valmis ajettavaksi:",
  loadError: "Ratkaisun mallia ei saatu ladattua:",
  role: "Rooli",
  yourTurn: "sinun vuorosi",
  yourTask: "Sinun tehtäväsi",
  nothingForYou: "Ei tehtäviä tälle roolille juuri nyt.",
  caseAt: "Tapaus on vaiheessa",
  ownedBy: "vastuussa",
  switchRole: "Vaihda rooliin",
  record: "Nauhoita",
  stop: "Lopeta nauhoitus",
  recording: "Nauhoitetaan…",
  upload: "Lataa tiedosto",
  remove: "Poista",
  uploading: "Ladataan…",
  micError: "Mikrofonia ei saatu käyttöön. Lataa tiedosto.",
  inputMissing: "Lisää syöte ennen lähettämistä.",
  note: "Viesti hyväksyjälle (valinnainen)",
  submit: "Lähetä",
  stepDone: "Valmis – seuraavalle",
  earlierSteps: "Aiemmat vaiheet",
  returnTo: "Palautetaan vaiheeseen",
  submitting: "Lähetetään…",
  returned: "Palautettu korjattavaksi:",
  failed: "Ajo ei onnistunut:",
  aiRunning: "Tekoäly käsittelee tapausta sandboxissa",
  aiRunningHint: "Kestää yleensä 1–3 minuuttia. Sivu päivittyy itsestään.",
  reviewTitle: "Tarkista ja hyväksy",
  source: "Lähde",
  transcript: "Litterointi",
  checks: "Tarkistukset",
  groundingOk: "Lähdetarkistus läpi",
  groundingBad: "Lähdetarkistus: mahdollisia keksittyjä arvoja",
  allValid: "Kaikki kentät kelvollisia",
  needFixing: "kenttää vaatii korjausta",
  uncertain: "epävarma",
  edited: "muokattu",
  notStated: "ei mainittu",
  ai: "Tekoäly:",
  restore: "palauta",
  required: "Pakollinen kenttä",
  allowed: "Sallitut arvot:",
  format: "Muoto:",
  listHint: "pilkuilla erotettu lista",
  approve: "Hyväksy",
  returnForFix: "Palauta korjattavaksi",
  reject: "Hylkää",
  restoreAll: "Palauta tekoälyn arvot",
  askReturn: "Mitä pitää korjata?",
  askReject: "Miksi tapaus hylätään?",
  cancel: "Peruuta",
  confirm: "Vahvista",
  returnNotInDiagram: "BPMN päättää hylkäyksen; palautus korjattavaksi on tapauksen oma sääntö.",
  approvedTitle: "Hyväksytty",
  completedTitle: "Tulos",
  item: "Tulos",
  addRow: "Lisää rivi",
  removeRow: "Poista rivi",
  jsonHint: "JSON",
  rejectedTitle: "Hylätty",
  export: "Vie",
  events: "Tapahtumat",
  roundLabel: "kierros",
  status: {
    draft: "Odottaa syötettä",
    running: "Tekoäly käsittelee",
    review: "Odottaa hyväksyntää",
    returned: "Palautettu",
    approved: "Hyväksytty",
    rejected: "Hylätty",
    failed: "Ajo epäonnistui",
    completed: "Valmis",
  },
  actions: {
    submit: "lähetti",
    result: "valmis",
    failed: "epäonnistui",
    approve: "hyväksyi",
    return: "palautti",
    reject: "hylkäsi",
    step: "antoi osuutensa",
  } as Record<string, string>,
  aiRole: "Tekoäly",
  designer: "Suunnittelijan näkymä",
  howBuilt: "Miten tämä näkymä on rakennettu",
  yourCases: "Sinun vuorosi",
  openCases: "Käynnissä",
  doneCases: "Valmiit",
  noneWaiting: "Ei tapauksia odottamassa sinua.",
  allCases: "Tapaukset",
  backToList: "Tapaukset",
  recordBig: "Aloita nauhoitus",
  recordAgain: "Nauhoita uudelleen",
  useRecording: "Käytä tätä nauhoitusta",
  sentTitle: "Lähetetty",
  sentHint: "Tekoäly käsittelee ilmoituksen, ja hyväksyjä saa sen tarkistettavaksi.",
  phasePending: "Käynnistetään eristettyä ajoa…",
  phaseRunning: "Ajo käynnissä",
  runLog: "Ajon loki",
  edit: "Muokkaa",
  preview: "Esikatselu",
  sourcePreview: "Lähde",
  closePreview: "Sulje",
  highlightHint: "Valitse kenttä, niin sen arvo korostuu lähteessä.",
};

const en: CaseStrings = {
  kicker: "Solution in use",
  intro: "Roles and steps come from the solution's BPMN, the form from the agreed output fields. The AI step runs in the sandbox on the case's own input.",
  back: "Back to the wizard",
  newCase: "New case",
  cases: "Cases",
  noCases: "No cases yet.",
  notReady: "The package is not ready to run yet:",
  loadError: "Could not load the solution's model:",
  role: "Role",
  yourTurn: "your turn",
  yourTask: "Your task",
  nothingForYou: "Nothing for this role right now.",
  caseAt: "The case is at",
  ownedBy: "owned by",
  switchRole: "Switch to role",
  record: "Record",
  stop: "Stop recording",
  recording: "Recording…",
  upload: "Upload file",
  remove: "Remove",
  uploading: "Uploading…",
  micError: "No microphone access. Upload a file instead.",
  inputMissing: "Add the input before submitting.",
  note: "Note to the reviewer (optional)",
  submit: "Submit",
  stepDone: "Done – to the next person",
  earlierSteps: "Earlier steps",
  returnTo: "Return to step",
  submitting: "Submitting…",
  returned: "Returned for correction:",
  failed: "The run did not succeed:",
  aiRunning: "The AI is processing the case in the sandbox",
  aiRunningHint: "Usually 1–3 minutes. The page updates by itself.",
  reviewTitle: "Review and approve",
  source: "Source",
  transcript: "Transcript",
  checks: "Checks",
  groundingOk: "Grounding check passed",
  groundingBad: "Grounding check: possible invented values",
  allValid: "All fields valid",
  needFixing: "field(s) need fixing",
  uncertain: "uncertain",
  edited: "edited",
  notStated: "not stated",
  ai: "AI:",
  restore: "restore",
  required: "Required field",
  allowed: "Allowed values:",
  format: "Format:",
  listHint: "comma-separated list",
  approve: "Approve",
  returnForFix: "Return for correction",
  reject: "Reject",
  restoreAll: "Restore AI values",
  askReturn: "What needs correcting?",
  askReject: "Why is the case rejected?",
  cancel: "Cancel",
  confirm: "Confirm",
  returnNotInDiagram: "The BPMN ends a rejection; returning for correction is the case's own rule.",
  approvedTitle: "Approved",
  completedTitle: "Result",
  item: "Result",
  addRow: "Add row",
  removeRow: "Remove row",
  jsonHint: "JSON",
  rejectedTitle: "Rejected",
  export: "Export",
  events: "Events",
  roundLabel: "round",
  status: {
    draft: "Awaiting input",
    running: "AI processing",
    review: "Awaiting approval",
    returned: "Returned",
    approved: "Approved",
    rejected: "Rejected",
    failed: "Run failed",
    completed: "Completed",
  },
  actions: {
    submit: "submitted",
    result: "done",
    failed: "failed",
    approve: "approved",
    return: "returned",
    reject: "rejected",
    step: "gave their part",
  },
  aiRole: "AI",
  designer: "Designer view",
  howBuilt: "How this view is built",
  yourCases: "Your turn",
  openCases: "In progress",
  doneCases: "Finished",
  noneWaiting: "Nothing is waiting for you.",
  allCases: "Cases",
  backToList: "Cases",
  recordBig: "Start recording",
  recordAgain: "Record again",
  useRecording: "Use this recording",
  sentTitle: "Sent",
  sentHint: "The AI is processing the report, then the reviewer gets it to check.",
  phasePending: "Starting the isolated run…",
  phaseRunning: "Run in progress",
  runLog: "Run log",
  edit: "Edit",
  preview: "Preview",
  sourcePreview: "Source",
  closePreview: "Close",
  highlightHint: "Pick a field and its value is highlighted in the source.",
};

export const CASE_STRINGS: Record<Locale, CaseStrings> = { fi, en };
